### ISSUE TITLE
FAQ has stale links for "Available datasets" & "Corpus Howto"

### ISSUE THREAD

**Issue by chrish42** [nltk/nltk.github.com#21]
The [NLTK FAQ](https://github.com/nltk/nltk/wiki/FAQ)'s question #5 ("What data sources does NLTK use?") has in its answer the following stale (404) links:
* http://nltk.org/nltk_data/ ("available datasets")
* http://nltk.org/howto/ ("Corpus Howto")

**Comment by tomaarsen** [comment]
I've updated the FAQ accordingly! Thank you for bringing this to our attention.
