### ISSUE TITLE
[off-topic] Organization permissions

### ISSUE THREAD

**Issue by turicas** [nltk/nltk.github.com#6]
It's not related to this repository but to nltk organization on GitHub. It's a security issue in my opinion.

The current setting allows members of the organization give access to its repositories to third-party applications even if the members are giving access to these applications for use in its own repositories (not in nltk's).
The default setting should be to avoid it and, if needed, grant access to certain third-party applications. To configure it an owner should:

- Go to https://github.com/organizations/nltk/settings/oauth_application_policy (Organization page > Settings > Third-party access)
- Click on "Setup application access restrictions"
- Click on "Restrict third-party application acess"

**Comment by stevenbird** [comment]
Thanks @turicas, this is now done.
