### ISSUE TITLE
Python version support should be updated

### ISSUE THREAD

**Issue by alvations** [nltk/nltk.github.com#9]
NLTK Python 3 support should be updated to 3.4+ as in the github repo: https://github.com/nltk/nltk/blob/develop/web/install.rst

Currently on the page: http://www.nltk.org/install.html and https://github.com/nltk/nltk.github.com/blob/master/install.html it's showing 3.2+

**Comment by MaxValue** [comment]
This issue has been resolved -> Pages are now showing the versions "2.7, 3.4, or 3.5" in unison.

**Comment by tomaarsen** [comment]
This has indeed been resolved.
